### ISSUE TITLE
project plan

### ISSUE THREAD

**Issue by parchment** [parchment/hark#1]
- [ ] what is hark
- [ ] who is hark for
- [ ] why is hark useful
- [ ] how does hark work
