### ISSUE TITLE
epic: client

### ISSUE THREAD

**Issue by parchment** [parchment/hark#13]
- [ ] authentication ui
- [ ] create basic task ui
- [ ] create basic habit ui
- [ ] show task/habit list
- [ ] manually reorder tasks/habits
- [ ] guide user through goal setting
- [ ] create task/habit dashboard
