### ISSUE TITLE
epic: server

### ISSUE THREAD

**Issue by parchment** [parchment/hark#29]
- [ ] create firebase project
- [ ] create user firestore
- [ ] create neo4j databases
- [ ] create basic user api
