### ISSUE TITLE
epic: task management

### ISSUE THREAD

**Issue by parchment** [parchment/hark#34]
- [ ] define task schema
- [ ] create task crud api
- [ ] convert task into habit
- [ ] schedule task
- [ ] create task dependencies
- [ ] generate task priority
- [ ] create task groups
