### ISSUE TITLE
epic: goal setting

### ISSUE THREAD

**Issue by parchment** [parchment/hark#42]
- [ ] define goal schema
- [ ] define prompt schema
- [ ] create goal crud api
- [ ] return prompts
- [ ] return goal structure
- [ ] generate task/habit from goal
