### ISSUE TITLE
epic: habit tracking

### ISSUE THREAD

**Issue by parchment** [parchment/hark#49]
- [ ] define habit schema
- [ ] create habit crud api
- [ ] convert habit into task
- [ ] schedule habit
- [ ] calculate progress
- [ ] create custom habit dependencies
- [ ] generate habit priority
